### PR TITLE
fixup libgfortran pc files

### PR DESCRIPTION
**Pull request by staticfloat**

### CODE REVIEW

**Comment by tkelman** [comment]
I think it's the ipopt pkg-config files that need patching, does gfortran even come with any of its own? Ipopt gets the libgfortran paths by linking an example Fortran program in verbose mode as a configure probe.

**Comment by staticfloat** [comment]
This is a function stored in `libgfortran.rb` that gets run by people that need it, so I don't have to copy the same fixup stuff into every dependent file.  See `ipopt.rb` for [an example](https://github.com/staticfloat/homebrew-juliadeps/blob/master/ipopt.rb#L19-L22), where we call the function I just extended in this file.

**Comment by tkelman** [comment]
oh my bad, didn't realize formulas could define functions for their dependents to use like that.

**Comment by staticfloat** [comment]
It's not normal; as far as I know it's not done anywhere else.

**Pull request merged**
