### PR TITLE
metis4: new formula.

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
I'm not sure if `keg_only` is relevant here (a PR with METIS 5 is coming). Also is the `test` method relevant?

**Comment by tkelman** [comment]
metis 4 has a pretty nonstandard and restrictive license, will want to make that clear anywhere you use it

**Comment by dpo** [comment]
Ok. What's the standard way to do that in Homebrew.jl? A `caveats` method?

**Comment by tkelman** [comment]
Not sure if it's necessary from the homebrew formula as much as in the documentation of packages where you plan to use it.

**Comment by dpo** [comment]
Oh right. My first use case is in HSL.jl, so restrictive licenses are going to pile up.

**Comment by tkelman** [comment]
Yeah, from HSL it's not so much of an issue since that's already not redistributable, but there's https://github.com/JuliaSparse/Metis.jl which will likely also want to use a Metis 5 bottle. Though since it looks like the homebrew-science bottles are `cellar :any` they probably don't need to be replicated here.

**Comment by dpo** [comment]
Can this Homebrew fetch Homebrew/Science bottles?

**Comment by tkelman** [comment]
I believe if you specify the full path, `homebrew/science/metis4` or something like that it should work. I used homebrew-science's cppad at build time in https://github.com/staticfloat/homebrew-juliadeps/blob/ce3d0c379a699ac7fc525193fa4ea0f0df096e38/optimizationservices.rb#L10, it may also work directly in the bindeps provides if things are relocatable.

**Comment by staticfloat** [comment]
Yes, an easy way to test it out is to just try running
Homebrew.add("homebrew/science/metis4") and see if it downloads bottles
properly. It shouldn't compile anything; that's a dead giveaway that
something is wrong.

**Comment by dpo** [comment]
Didn't realize `Homebrew.add` could tap. It works! Might be worth mentioning this in Homebrew.jl's README. Thanks!

**Comment by staticfloat** [comment]
Great, since that works, I'm assuming this can be closed?  I added some more documentation in https://github.com/JuliaLang/Homebrew.jl/commit/9b34496c4dd736bf677b1f487066ae4cfd98a448

**Comment by dpo** [comment]
Excellent. Many thanks!

**Comment by dpo** [comment]
On the other hand, `Homebrew.rm("homebrew/science")` doesn't seem to work.

**Comment by staticfloat** [comment]
Try either `Homebrew.rm("homebrew/science/metis4")` or `Homebrew.rm("metis4")`.

Once it's installed, you don't need to bother with the namespacing.

**Comment by dpo** [comment]
I meant to untap. I can do `run(`$(Homebrew.brew) untap homebrew/science`)` but it seems a little hackish.

**Comment by dpo** [comment]
Sorry I think I'm hitting another difficulty. `metis4` is `keg_only` because it conflicts with `metis` (version 5). That means it's not linked in `~/.julia/v0.4/Homebrew/deps/usr/lib`. So BinDeps isn't happy. Is there a way to deal with `keg_only` formulae? I'd have to obtain the path to the library (in its cellar or in `opt`) inside `build.jl`. Is there a way to do that?

**Comment by staticfloat** [comment]
I don't think it's necessary to untap; why do you want to do that?  If you'd like, we can add a `Homebrew.untap()` call, but honestly there's no downside to keeping taps around that I can think of.

To deal with `keg_only` formulae, you should use the `Homebrew.prefix()` function to find the prefix of the particular formula you want to access.  You can see an example of this in [Imagemagick here](https://github.com/JuliaIO/ImageMagick.jl/blob/master/deps/build.jl#L83-L84), basically you can do things like `push!(DL_LOAD_PATH, joinpath(Homebrew.prefix("metis4"), "lib"))` to be able to load dynamic libraries from the lib folder.

**Comment by dpo** [comment]
Phew! Many thanks for all the help!! I've got something working now.

I agree it shouldn't be necessary to untap. It was for debugging purposes.

**Comment by lewisl** [comment]
Yes.

On Oct 12, 2015, at 10:26 PM, Elliot Saba <notifications@github.com<mailto:notifications@github.com>> wrote:


Great, since that works, I'm assuming this can be closed? I added some more documentation in JuliaLang/Homebrew.jl@9b34496<https://github.com/JuliaLang/Homebrew.jl/commit/9b34496c4dd736bf677b1f487066ae4cfd98a448>

**Pull request closed without merging**
