### PR TITLE
Update pixman.rb to fix `mmx`-related error in El Capitan

### PR DESCRIPTION
**Pull request by mseri**
The fix is already upstram on homebrew - reference commit: https://github.com/Homebrew/homebrew/commit/23a2c738a7286ea862daa86eee900585de17fb57

### CODE REVIEW

**Comment by staticfloat** [comment]
Thank you, @mseri!  Note that we are not building bottles for El Capitan quite yet, so users will still have to install from source.

**Comment by lewisl** [comment]
@staticfloat Unfortunately, that means Mac users can't get this pull request.  The Julia Pkg manager for OS X only gets binaries from home-brew--there is no command to build a commit from source in Homebrew.jl.  It only runs a formula--no way to grab another formula or build from source.

**Comment by staticfloat** [comment]
@lewisl I've merged the changes into `master` as it doesn't break anything that wasn't already broken.  Please let me know if the compilation error continues for you.

**Comment by lewisl** [comment]
Awesome.  It works.  Had to clear packages to force a clean re-build and it was successful.

Thank You!


On Oct 5, 2015, at 6:13 PM, Elliot Saba <notifications@github.com<mailto:notifications@github.com>> wrote:


@lewisl<https://github.com/lewisl> I've merged the changes into master as it doesn't break anything that wasn't already broken. Please let me know if the compilation error continues for you.

**Pull request merged**
