### PR TITLE
COIN-OR Optimization Services

### PR DESCRIPTION
**Pull request by tkelman**
This is a WIP because the package I'm working on isn't done yet, it's not yet registered but source builds of the dependencies are working on Travis for both Linux and OSX, modulo Linux libgfortran issues. For Homebrew bottling, this builds upon Ipopt (which is for continuous nonlinear problems) and Cbc (which is for mixed-integer linear problems) with the Bonmin and Couenne mixed-integer nonlinear solvers, the CppAD header-only library for automatic differentiation, and the Optimization Services client.

I think this makes sense as 4 separate formulae, since it's possible in the future someone may want to use Cxx.jl to write direct in-memory interfaces to just Bonmin, or just Couenne, without needing Optimization Services. There are also 2 different types of tarballs for these packages, one bundling all dependencies and one standalone. The standalone tarballs make more sense in combination with a package manager like homebrew, since pkg-config handles everything properly. If we were to use the bundled tarball for this, it would be messier to reuse the Ipopt and Cbc binaries that we already have. We'd also be building some extra libraries that I don't care as much about at the moment, but those can always be added later.

CppAD (and Ipopt for that matter) is included in homebrew-science and has started being bottled there, so it might make sense to just use their binaries for that. Do we have any Julia packages currently using homebrew-science dependencies via Homebrew.jl?

### CODE REVIEW

**Comment by staticfloat** [comment]
Looks pretty decent to me.  If you're ready, I'll merge and bottle this weekend, hopefully.

**Comment by tkelman** [comment]
Thanks for the review. @mlubin do you have any input on these?

Upstream is fairly likely to do another few point releases in the near future but I don't expect major changes. I guess updates are easy enough later so may as well get some binaries going for testing whenever is convenient for you.

**Comment by mlubin** [comment]
LGTM. By using the pkgsource versions for bonmin, etc., are we depending on the fact that for Cbc we use the bundled tarball?
Would be nice to follow along with homebrew-science, but I'll let @staticfloat decide if that makes sense.

**Comment by tkelman** [comment]
> By using the pkgsource versions for bonmin, etc., are we depending on the fact that for Cbc we use the bundled tarball?

Not really. If we were to switch from bundled Cbc to separate pkgsource versions for CoinUtils, Osi, Clp, Cgl, and Cbc (which I think is what @tkralphs was wanting to play with, see if linuxbrew could work too), then each of those should depend on its predecessor and installing a Cbc built that way should bring along all of its dependencies which would be good enough for Bonmin.

> Would be nice to follow along with homebrew-science

I could try just using homebrew-science's version of cppad and see if that works (at least on Travis). I suspect it would build okay but I'm not positive whether Homebrew.jl would handle it seamlessly.

**Comment by tkralphs** [comment]
Thanks @tkelman for making me aware of this conversation. I didn't realize you guys were developing homebrew recipes for COIN projects here. I guess you are already aware there are some recipes in [homebrew-science](https://github.com/Homebrew/homebrew-science) and there is also a mostly empty repo intended to contain the "official" homebrew recipes for COIN-OR projects [here](https://github.com/coin-or/homebrew-coinor). 

So I guess the obvious question is whether you guys are creating these recipes as a temporary measure until the "official" recipes are available or whether you think maintaining a separate set of recipes makes sense. I'm honestly not sure what the community standards are w.r.t fragmentation/duplication. It seems to me that maintaining one set of recipes is preferable overall, but I can also see the advantage for you of having recipes for all your dependencies in one repo. I'd appreciate knowing your thoughts on this.

As for the specific question here, pkgsource versus source, my vision was to have a full set of recipes built from pkgsource and to let the dependency mechanism for homebrew take care of recursively installing all required packages. I guess one could argue that there is only a certain level of granularity one needs. For example, it is unlikely anyone will want to install [CoinUtils](projects.coin-or.org/CoinUtils) on its own. But it is possible someone would want to install Osi on its own and that is only one level up in the dependency hierarchy.

Creating a full set of recipes for all projects built from pkgsource would probably not take a whole lot of effort. To be honest, what has been holding me up is the third party codes. I guess the way that you are handling those is fine (just use the COIN wrappers), but I was wondering if we should just try to depend directly on any existing recipes for those projects.

For you guys, it makes sense to install Cbc monolithically, but I guess I am wondering if this will cause problems down the road. If someone installs your Cbc recipe and then later tries to install what they think is a completely unrelated project (such as [SYMPHONY](projects.coin-or.org/SYMPHONY) or [DIP](projects.coin-or.org/Dip)) that has some of the same underlying dependencies, this will create conflicts and there won't be any easy way to resolve them.

We can talk about this at our Monday meeting, but it seems like the solution is to install all projects as pkgsource and just maintain recipes for all the dependencies separately. I don't think this is as onerous as it sounds and will make a lot of things easier. We should definitely coordinate our efforts, though, in the meantime.

**Comment by staticfloat** [comment]
Hello there, Ted Ralphs!  Glad to have you as a part of the conversation.

The main reason to have this repository is for [bottling](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Bottles.md).  Specifically, every formula in this repository is here only because there is not already a relocatable (e.g. `Cellar: any`) bottle already defined in another Homebrew repository.  We go through pains to patch/provide environment variables to software packages to make them relocatable and therefore installable on user's machines without sudo access.  In particular, with Julia, we install everything to `~/.julia`, which is of course a different path on every user's machine.

The end result of this is that users can get at these binary packages without having a compiler toolchain installed.  It does result in this repository lagging behind the bleeding edge a little bit, but that's unavoidable at this point as there are a few manual steps involved every time we need to build a new bottle.

**Comment by mlubin** [comment]
@tkralphs, in addition to what @staticfloat said, another reason why we can't share the same scripts with homebrew-science (for the time being) is that we need to handle BLAS/LAPACK in a nonstandard way to avoid conflicts with Julia's version of BLAS/LAPACK which uses 64-bit integers.

**Comment by staticfloat** [comment]
Ah, yes.  Excellent point.  We seem to have taken the rebel's stance on 64-bit indexed BLAS functions and changed the BLAS names accordingly.  Many software packages provide a nice way of dealing with this, as seen in [this scs formula](https://github.com/staticfloat/homebrew-juliadeps/blob/2724feff65b333d63d78102b861ec5a89ec0f977/scs.rb#L25).

**Comment by tkralphs** [comment]
OK, thanks for the explanation, I see. This doesn't look like it should cause any conflicts and it does seem to make sense for you guys to have separate recipes.

**Comment by tkelman** [comment]
I do think a little bit of duplication between here and homebrew-science is inevitable. Homebrew-science only recently started providing binary bottles, and generally has many more customization options available in terms of different blas implementations, mpi, etc. Whereas for Julia packages, we're trying to provide just the binaries configured in a predictable uniform way, so that users don't have to think too much when they install the wrapper packages and things just work - even if those users don't have compilers installed on their own system.

It would probably be a good idea to contribute some of what we're doing in terms of formula granularity back to either homebrew-science (last I checked they're still using a coinmp formula which hasn't been updated in a while, and is marked as conflicting with other coin packages due to the dependency bundling) or the homebrew-coinor tap. I went and fixed the issue with conflicting blas integer sizes in Julia a few months ago, since it was a familiar problem that I had been hitting with Ipopt and Matlab for several years. The original packaging of Ipopt in this tap predated the fix there - we could actually get rid of our workarounds now, though we'd have to remember to impose a higher minimum Julia version requirement on the Ipopt package if we did so.

**Comment by tkelman** [comment]
Note to @staticfloat - I'll want to bump the optimizationservices.rb formula to a just-released upstream version, as soon as OSX builds come back on Travis CI so I can verify it works okay on that platform. And I might want to carry a local patch for a bug I just found - http://list.coin-or.org/pipermail/os/2015-January/000211.html

The other 3 should be okay, there might be more new point releases of them soon but I don't think they'll be fixing major bugs. Most of the issues I'm finding have been in the OS interfaces so far.

**Comment by tkelman** [comment]
Oh dear. On Linux, trying to use the latest 2.9.0 of OS failed one of its unit tests, related to Cbc. Updating Cbc to its latest 2.9.0 fixed the problem on Linux, but fails to build on OSX because of the new CoinRational.cpp and use of undeclared identifier 'labs'. I think that's been fixed but isn't yet in a released version of CoinUtils. I wonder why the latest release version of OS didn't trigger a new release of CoinUtils, since there have been a few commits in CoinUtils stable...

**Comment by tkralphs** [comment]
@tkelman Yes, the bug you referred to on OS X (undefined function '''labs''') has been fixed in CoinUtils stable ('''labs''' is in a non-standard header file location on OS X) and I will hopefully get out a new release this weekend. What is holding things up is a rather unfortunate problem I found with build tools that I will be talking to you about off-line.

At the moment, none of the .0 releases build on OS X. Sorry, that failure somehow slipped through the cracks. As for why nothing was triggered when the OS release was done, it was a combination of my not having caught the problem myself and that our procedures don't really strictly enforce testing by PMs on all platforms. Generally, if it builds and passes unit test on at least one platform, the PM can release it (not really conscious policy as much as that the release script just gets run on one platform). Though not ideal, this has generally worked OK, since I'm doing the releases for most of the projects myself (and even if not, I am building and testing projects on all platforms). But in this case, a bug slipped through. I'm working on beefing up our procedures in this regard, but in the end, this is a result of the fact that none of the PMs, aside from me, regularly develop on OS X.

**Comment by tkelman** [comment]
@tkralphs one thing we can probably do that might not be too hard is set up Travis CI for our Github mirrors, that would give us testing on Linux and (if you send them an email) OSX. And we can try AppVeyor too for Windows. Though some of the COIN libraries are pretty big and might start hitting the time limit on Windows.

I was about to send you and the TLC list an email saying dependency linking wasn't working, but then saw you'd committed a fix to BuildTools already. Also note that Cbc 2.9.0 is segfaulting with SOS constraints, see https://github.com/JuliaOpt/Cbc.jl/pull/26 - hopefully we can come up with a standalone reproduction case that doesn't depend on Julia.

**Comment by tkelman** [comment]
I'm going to close this for now, until there's a new round of upstream releases and we get a chance to thoroughly test them. I would be good to get an opinion on how Homebrew.jl might interact with bottles provided by homebrew-science.

And note for @tkralphs, it looks like trunk of Couenne and OS, and the latest stable of Couenne, have not had their externals/Dependencies updated to latest stables.

**Comment by staticfloat** [comment]
Homebrew.jl can install bottles from other sources as long as they're `Cellar: any`; in fact, that's what happens for a lot of formulae from mainline Homebrew.  Let me know when the next round of releases happens, these formulae look good so far, so we'll just have to update some URLs and SHAs, and we'll be good to build.

**Comment by tkelman** [comment]
Does the formula have to explicitly say `Cellar: any`? If not, is there any way to tell if/when a formula satisfies that requirement? How would a Julia package's BinDeps script need to be modified to refer to a formula from homebrew-science (or homebrew-coinor, if we build bottles there)? I haven't looked into the internals of how Homebrew.jl works, but I'm guessing you might be hardcoding adding this tap somewhere?

**Comment by staticfloat** [comment]
> Does the formula have to explicitly say Cellar: any?

Yes.  Anything that doesn't say that failed brew's automatic relocation detection.  Sometimes that doesn't matter, sometimes it matters a lot.  I've done a bit of work improving that relocation code in the past, so it will deal with things like `.la` files, `.dylib` RPATH entries, etc... intelligently.  Things like documentation that have hardcoded paths built at buildtime can cause it to fail, which we don't care about, but things like hardcoded paths in binaries will look the same to it.  When you build a bottle, brew will print out a little summary of what is not relocatable and why; that's the important part.  Here's an example from [a recent build of graphviz](http://buildbot.e.ip.saba.us:8010/builders/bottle_osx10.8/builds/61/steps/shell/logs/stdio):
```
==> Detecting if graphviz-2.38.0_1.mountain_lion.bottle.tar.gz is relocatable...
Warning: String '/usr/local/Cellar' still exists in these files:
/usr/local/Cellar/graphviz/2.38.0_1/lib/graphviz/tcl/libtcldot_builtin.0.dylib
 --> match '/usr/local/Cellar/graphviz/2.38.0_1/lib/graphviz' at offset 0xdd55c
/usr/local/Cellar/graphviz/2.38.0_1/lib/libgvc.6.dylib
 --> match '/usr/local/Cellar/graphviz/2.38.0_1/lib/graphviz' at offset 0x50dc5
/usr/local/Cellar/graphviz/2.38.0_1/lib/libgvpr.2.dylib
 --> match '.:/usr/local/Cellar/graphviz/2.38.0_1/share/graphviz/gvpr' at offset 0x4358e
```

This is a problem, but we can get around it with the proper environment variables.

> How would a Julia package's BinDeps script need to be modified to refer to a formula from homebrew-science (or homebrew-coinor, if we build bottles there)?

You can do things like say `Homebrew.add("homebrew/science/a5")` (to take the first example I found):
```
julia> Homebrew.add("homebrew/science/a5")
Cloning into '/Users/sabae/.julia/v0.3/Homebrew/deps/usr/Library/Taps/homebrew/homebrew-science'...
remote: Counting objects: 8637, done.
remote: Total 8637 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (8637/8637), 2.16 MiB | 533.00 KiB/s, done.
Resolving deltas: 100% (4809/4809), done.
Checking connectivity... done.
Warning: Could not create link for homebrew/science/hdf5, as it
conflicts with staticfloat/juliadeps/hdf5. You will need to use the
fully-qualified name when referring this formula, e.g.
  brew install homebrew/science/hdf5
Warning: Could not create link for homebrew/science/hwloc, as it
conflicts with staticfloat/juliadeps/hwloc. You will need to use the
fully-qualified name when referring this formula, e.g.
  brew install homebrew/science/hwloc
Warning: Could not create link for homebrew/science/ipopt, as it
conflicts with staticfloat/juliadeps/ipopt. You will need to use the
fully-qualified name when referring this formula, e.g.
  brew install homebrew/science/ipopt
Warning: Could not create link for homebrew/science/netcdf, as it
conflicts with staticfloat/juliadeps/netcdf. You will need to use the
fully-qualified name when referring this formula, e.g.
  brew install homebrew/science/netcdf
Warning: Could not create link for homebrew/science/nlopt, as it
conflicts with staticfloat/juliadeps/nlopt. You will need to use the
fully-qualified name when referring this formula, e.g.
  brew install homebrew/science/nlopt
Tapped 424 formulae
==> Installing a5 from homebrew/homebrew-science
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/science/a5-20141120.yosemite.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring a5-20141120.yosemite.bottle.1.tar.gz
🍺  /Users/sabae/.julia/v0.3/Homebrew/deps/usr/Cellar/a5/20141120: 30 files, 8.5M
To relink: brew unlink a5 && brew link a5
```

Notice how it automatically taps `homebrew/science`.  This unfortunately is not my genius, but is instead just how `brew` works.  Note also how formulae that my tap offers conflict with `homebrew/science`.  Because my tap is always tapped immediately after `Homebrew.jl` installation, they take precedence, meaning that if I were to simple do `Homebrew.add("nlopt")` it would choose mine.  However, if you have tapped `homebrew/science` in the past, then update `Homebrew.jl`, which pulls in the latest version of the tap, and I've added a new formula which is already provided by `homebrew/science`, it will not overwrite the precedent set by `homebrew/science`.  This is why I suggest always fully-qualifying homebrew formula names when necessary, e.g. `staticfloat/juliadeps/cairo`.  When dealing with formulae from the mainline repository of course, there is no fully qualified name to use.

> I'm guessing you might be hardcoding adding this tap somewhere?

The only hardcoded tap is `staticfloat/juliadeps`.  Everything else is dynamic.  Death to hardcoding!

**Comment by tkelman** [comment]
Would be good to bump and bottle the latest cbc at least. The rest are still pending, and there's a patch that'll be in the next release of Ipopt that I'll want to have. Can either merge this or split cbc out into a separate PR since only Cbc is ready for bottling right now, I'll let you know when the rest are ready.

**Comment by staticfloat** [comment]
`cbc` bottles are now building.  Note that I do most of my changes on the `staging` branch, and then once bottles are built I merge the result into `master` so that we have zero downtime.

**Comment by staticfloat** [comment]
`cbc` bottles [built and uploaded](https://github.com/staticfloat/homebrew-juliadeps/pull/37).

**Comment by tkelman** [comment]
Lovely, thank you, I'll rebase that bit out when it's time for the rest of these.

**Comment by staticfloat** [comment]
I'm not sure you'll even need to, since I cherry-picked your commit.  At
the very least, you should be able to `git pull --rebase` and your commit
should just silently disappear.  I THINK that will happen.  :P

**Comment by tkelman** [comment]
Bonmin and an Ipopt version bump should be ready for cherry-picking into staging. Bonmin depends on Ipopt so probably better to bump the Ipopt bottle first.

**Comment by staticfloat** [comment]
Bottles ahoy. Ipopt tests pass.

**Comment by tkelman** [comment]
Thanks! :anchor:

**Comment by mlubin** [comment]
@tkelman, are there currently any remaining glaring issues upstream that would prevent packaging?

**Comment by tkelman** [comment]
I don't think the issue with maximization-sense MINLP's in OS has been addressed, and there's the major performance differential in the AD, but I may as well bump the 3 remaining versions, thanks for the reminder.

**Comment by mlubin** [comment]
The performance differential doesn't seem like show stopper for me, since there's no need to use Ipopt through OS, and hopefully the MINLPs which people may want to solve with Bonmin are relatively small. 
For the maximization issue, I would just flip the sign in CoinOptServices.jl or even throw an error and let users flip the sign in their models.

I think the Bonmin/Couenne interfaces through OS will already be quite useful for many people as they are, so my vote would be to release/announce (as experimental) basically as is and see what kinds of issues people start running into. That seems to be the JuliaOpt philosophy, at least :)

**Comment by tkelman** [comment]
Oh yeah, I guess I never announced the package anywhere. Issue number 1 did get filed, but turned out to be a model that could be reformulated as linear. Taking a look at the osil files is really useful.

**Comment by tkelman** [comment]
I do have it throwing a warning https://github.com/tkelman/CoinOptServices.jl/blob/e25774159f5efdc0b65c4fa2273e57c0c2e7fb9e/src/CoinOptServices.jl#L500-L506
Manipulating the user's provided objective felt like a little much. Or there was some complication, doing it nicely across both linear objectives (if only constraints were nonlinear) and nonlinear ones was too messy or something... and now I'm also wondering whether the same bug could also hit QCQP's for which I don't think that warning will trigger.

It looks like the homebrew/science/cppad formula has a cellar-any bottle, so may as well try using it.

**Comment by tkelman** [comment]
@staticfloat I think these should be gtg, if I could retarget this PR to be against staging I would.

**Comment by staticfloat** [comment]
I've squashed these and applied them to `staging`, building bottles now.  On a completely unrelated note, I think `couenne` has to be one of the most beautiful names for a software package ever.

**Comment by staticfloat** [comment]
Looks like we've got some `couenne` compilation problems on 10.8.  We're hitting SIGABRTS whenever we run couenne code.... :/

**Comment by tkelman** [comment]
Oh dear. Can that be caught in lldb?

**Comment by staticfloat** [comment]
It's weird.  It's only happening on 10.8.  I can reproduce it by running `couenne` on one of the test data sets.  Example `lldb` session:

```
$ lldb -- $(which couenne) circle.nl                                                                                                          [7/235]
Current executable set to '/usr/local/bin/couenne' (x86_64).
(lldb) r
Process 74177 launched: '/usr/local/bin/couenne' (x86_64)
Couenne 0.5.2 -- an Open-Source solver for Mixed Integer Nonlinear Optimization
Mailing list: couenne@list.coin-or.org
Instructions: http://www.coin-or.org/Couenne

NLP0012I
              Num      Status      Obj             It       time                 Location
NLP0014I             1         OPT 203.06834       10 0.009223
Coin0506I Presolve 6 (-5) rows, 2 (-6) columns and 12 (-11) elements
Clp0006I 0  Obj 203.06834 Primal inf 0.032473934 (5)
Clp0006I 1  Obj 203.06834
Clp0000I Optimal - objective value 203.06834
Clp0032I Optimal objective 203.0683375 - 1 iterations time 0.002, Presolve 0.00
Clp0000I Optimal - objective value 203.06834
Cbc0012I Integer solution of 203.06834 found by Couenne Rounding NLP after 0 iterations and 0 nodes (0.00 seconds)
NLP0014I             2         OPT 203.06834        8 0.00626
Cbc0001I Search completed - best objective 203.0683375796171, took 0 iterations and 0 nodes (0.01 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Clp0000I Optimal - objective value 203.06834

couenne: Optimal

        "Finished"
Total solve time:                        0.009888s (0.009889s in branch-and-bound)
Lower bound:                              203.068
Upper bound:                              203.068  (gap: 0.00%)
Branch-and-bound nodes:                         0
couenne(74177) malloc: *** error for object 0x7fff77831570: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Process 74177 stopped
* thread #1: tid = 0x290684, 0x00007fff90d72d46 libsystem_kernel.dylib`__kill + 10, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007fff90d72d46 libsystem_kernel.dylib`__kill + 10
libsystem_kernel.dylib`__kill + 10:
-> 0x7fff90d72d46:  jae    0x7fff90d72d4d            ; __kill + 17
   0x7fff90d72d48:  jmpq   0x7fff90d744d4            ; cerror_nocancel
   0x7fff90d72d4d:  ret
   0x7fff90d72d4e:  nop
(lldb) bt
* thread #1: tid = 0x290684, 0x00007fff90d72d46 libsystem_kernel.dylib`__kill + 10, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007fff90d72d46 libsystem_kernel.dylib`__kill + 10
    frame #1: 0x00007fff8ee05f83 libsystem_c.dylib`abort + 177
    frame #2: 0x00007fff8edd9989 libsystem_c.dylib`free + 392
    frame #3: 0x0000000100af5c4e libipopt.1.dylib`Ipopt::RegisteredOption::~RegisteredOption() + 232
    frame #4: 0x0000000100af46b7 libipopt.1.dylib`Ipopt::RegisteredOption::~RegisteredOption() + 15
    frame #5: 0x000000010027d4e5 libbonmin.4.dylib`std::_Rb_tree<std::string, std::pair<std::string const, Ipopt::SmartPtr<Ipopt::RegisteredOption> >, std::_Select1st<std::pair<std::string const, Ipopt::SmartPtr<Ipopt::RegisteredOption> > >, std::less<std::string>, std::allocator<std::pair<std::string const, Ipopt::SmartPtr<Ipopt::RegisteredOption> > > >::_M_destroy_node(std::_Rb_tree_node<std::pair<std::string const, Ipopt::SmartPtr<Ipopt::RegisteredOption> > >*) + 37
    frame #6: 0x0000000100270154 libbonmin.4.dylib`std::_Rb_tree<std::string, std::pair<std::string const, Ipopt::SmartPtr<Ipopt::RegisteredOption> >, std::_Select1st<std::pair<std::string const, Ipopt::SmartPtr<Ipopt::RegisteredOption> > >, std::less<std::string>, std::allocator<std::pair<std::string const, Ipopt::SmartPtr<Ipopt::RegisteredOption> > > >::_M_erase(std::_Rb_tree_node<std::pair<std::string const, Ipopt::SmartPtr<Ipopt::RegisteredOption> > >*) + 48
    frame #7: 0x0000000100270145 libbonmin.4.dylib`std::_Rb_tree<std::string, std::pair<std::string const, Ipopt::SmartPtr<Ipopt::RegisteredOption> >, std::_Select1st<std::pair<std::string const, Ipopt::SmartPtr<Ipopt::RegisteredOption> > >, std::less<std::string>, std::allocator<std::pair<std::string const, Ipopt::SmartPtr<Ipopt::RegisteredOption> > > >::_M_erase(std::_Rb_tree_node<std::pair<std::string const, Ipopt::SmartPtr<Ipopt::RegisteredOption> > >*) + 33
    frame #8: 0x0000000100270145 libbonmin.4.dylib`std::_Rb_tree<std::string, std::pair<std::string const, Ipopt::SmartPtr<Ipopt::RegisteredOption> >, std::_Select1st<std::pair<std::string const, Ipopt::SmartPtr<Ipopt::RegisteredOption> > >, std::less<std::string>, std::allocator<std::pair<std::string const, Ipopt::SmartPtr<Ipopt::RegisteredOption> > > >::_M_erase(std::_Rb_tree_node<std::pair<std::string const, Ipopt::SmartPtr<Ipopt::RegisteredOption> > >*) + 33
    frame #9: 0x000000010026ff95 libbonmin.4.dylib`Ipopt::RegisteredOptions::~RegisteredOptions() + 41
    frame #10: 0x0000000100270037 libbonmin.4.dylib`Bonmin::RegisteredOptions::~RegisteredOptions() + 15
    frame #11: 0x0000000100af431f libipopt.1.dylib`Ipopt::OptionsList::~OptionsList() + 87
    frame #12: 0x0000000100af3c6b libipopt.1.dylib`Ipopt::OptionsList::~OptionsList() + 15
    frame #13: 0x0000000100201b93 libbonmin.4.dylib`Bonmin::BabSetupBase::~BabSetupBase() + 389
    frame #14: 0x0000000100008eb4 couenne`main + 7044
```

It kinda looks like `ipopt` is screwing something up here.  I tried rebuilding `ipopt` but it still happens.

**Comment by tkelman** [comment]
Thanks for looking into this, I know you've been really busy lately. Does Homebrew default to different C++ standard libraries for 10.8 vs later? Out of the developers of Ipopt, Bonmin, and Couenne, I'm not sure which if any use Macs regularly. I know Ted does, in case he has any ideas here. His main development machine is on Yosemite though I believe.

In this case it looks like the solver finished, the issue is during a destructor that's running in the cleanup process. Ipopt uses smart pointers pervasively, it's possible either Bonmin or Couenne might be either misusing the Ipopt smart pointers in some way, or there could be some library/compiler mismatch in how the different components got built.

**Comment by mlubin** [comment]
I built Couenne from scratch on 10.7 and can't reproduce the issue.

**Comment by tkelman** [comment]
Closing this since the content is all on staging. About to open a new PR against staging, since there's a Couenne 0.5.3 now that we may as well try.

**Pull request closed without merging**
