### PR TITLE
fixup missing flag for SCS

### PR DESCRIPTION
**Pull request by joehuchette**
@mlubin helped track down this missing flag that caused some [Travis failures](https://travis-ci.org/JuliaOpt/JuMP.jl/jobs/68340559).

### CODE REVIEW

**Comment by mlubin** [comment]
CC @bodono. Missing this could cause memory corruption, right?

**Comment by bodono** [comment]
Yeah, because julia could garbage collect away the A matrix when SCS does not to keep a local copy.

**Comment by tkelman** [comment]
good catch

**Comment by staticfloat** [comment]
I love how quick to compile this library is.  :)

**Comment by tkelman** [comment]
Seriously, I think my turnaround between @madeleineudell asking to build a new version and having it ready was about 4 minutes. Also many thanks to @bodono for also updating my notes-to-self comments so the flags were right https://github.com/JuliaOpt/SCS.jl/commit/a1a70469f5b9581a5f8cec89ee80291339bbddc5

**Comment by bodono** [comment]
:+1:

**Pull request merged**
