### PR TITLE
attempt to fix CoinOptServices post rename

### PR DESCRIPTION
**Pull request by tkelman**
not sure if this needs revisioning? ref https://github.com/JuliaOpt/CoinOptServices.jl/issues/22

### CODE REVIEW

**Comment by tkelman** [comment]
cc @staticfloat ?

**Comment by tkelman** [comment]
ping again, does this need any additional action in terms of rebottling?

**Comment by tkelman** [comment]
it would at least need pushing to master at a minimum, right? i opened this against staging to be on the safe side

**Comment by staticfloat** [comment]
Yes, I am testing it on `staging`, but `Ipopt` needs fixing first.

**Comment by tkelman** [comment]
roger, thanks

**Comment by tkelman** [comment]
roger, thanks

**Comment by tkelman** [comment]
roger, thanks

**Comment by staticfloat** [comment]
A'ight, it's working.  Time to merge `staging` into `master`.

**Pull request merged**
