### PR TITLE
(partially) tag scs v1.1.5

### PR DESCRIPTION
**Pull request by joehuchette**
cc @tkelman, I think this is the requisite information.

### CODE REVIEW

**Comment by joehuchette** [comment]
Ref #50

**Comment by tkelman** [comment]
@staticfloat can confirm, but I think the perfect version would be deleting `revision` and leaving in

```
    root_url 'https://juliabottles.s3.amazonaws.com'
    cellar :any
```

**Comment by staticfloat** [comment]
Indeed, you can remove any `revision` tags that you see, and just delete the `sha` lines in the bottle stanza, leaving it like so:

```
  bottle do
    root_url 'https://juliabottles.s3.amazonaws.com'
    cellar :any
  end
```

**Comment by joehuchette** [comment]
Cool, thanks guys

**Comment by staticfloat** [comment]
Bam.  Nice.  Let's build 'em.

**Comment by joehuchette** [comment]
Whoops! wrong SHA1. Shame on me...

I'll update it now, but it's ``da69bd7dda2842ea6ce1640589c45c155c8c9a75`` for reference.

**Pull request merged**
