### PR TITLE
Couenne 0.5.3

### PR DESCRIPTION
**Pull request by tkelman**
ref #36, may as well try this version, see if it helps

### CODE REVIEW

**Comment by staticfloat** [comment]
Let's give it a shot!

**Comment by tkelman** [comment]
what's happening with http://buildbot.e.ip.saba.us:8010/builders/bottle_osx10.10/builds/82 ?

**Comment by staticfloat** [comment]
Not sure ATM, hope to look at this over spring break.  I'll be out of town
for the next two weeks, but will probably have a moment or two to look at
this.  :)
-E

**Comment by staticfloat** [comment]
Couenne seems to be building okay now, but bonmin is [giving me trouble on 10.8](http://buildbot.e.ip.saba.us:8010/builders/bottle_osx10.8/builds/74/steps/shell/logs/stdio).

**Comment by tkelman** [comment]
Hm, thanks for looking into it. Similar-looking double free to what couenne was giving before? Similar backtrace to before? If it can't be reproduced outside of homebrew, then maybe bottle bonmin everywhere except 10.8, if that's possible?

**Comment by mlubin** [comment]
Yeah, I think it's okay to just not make the bottles available on 10.8 until we can get access to a 10.8 machine and debug this.

**Comment by tkelman** [comment]
@mlubin if you feel especially motivated to help debug an assertion failure in Osi by way of Bonmin, see http://list.coin-or.org/pipermail/bonmin/2015-April/000424.html - it only happens in a debug build or when assertions are otherwise enabled, and apparently the Windows binaries from openSUSE have assertions on by default so I've been seeing this with the WinRPM builds of CoinOptServices for a while.

**Comment by mlubin** [comment]
@tkelman, will add to TODO list

**Comment by mlubin** [comment]
This is a tough one, not sure if I can figure out the issue without understanding exactly how branching works in bonmin. My first question is why we would have a solution at any point which doesn't satisfy the bounds.
My inclination would be to just patch this away unless there's a response on the Bonmin list.

**Comment by staticfloat** [comment]
Do we have an idea on how to patch this?

**Comment by mlubin** [comment]
Oh, just remove the assert :)

**Comment by tkelman** [comment]
Or figure out why asserts are being enabled in the Windows build and disable them.

I think bonmin tightens bounds and sends problems lower down the stack that probably should be eliminated earlier with some simple bound checks. I had to tweak Ipopt a little recently to catch an invalid-bounds assertion for a similar reason.

**Pull request merged**
