### PR TITLE
Bump optimizationservices and friends

### PR DESCRIPTION
**Pull request by staticfloat**

### CODE REVIEW

**Comment by staticfloat** [comment]
@tkelman @mlubin 

```
julia> dlopen("libOS")
Ptr{Void} @0x00007fb5a40da2b0

```

**Comment by tkelman** [comment]
Segfaults while building Cbc on Travis? https://travis-ci.org/tkelman/CoinOptServices.jl/jobs/58487034

**Comment by tkelman** [comment]
works on 0.3 though

**Comment by staticfloat** [comment]
Welp, that's annoying.  That looks remarkably similar to what I [see in `bonmin` on OSX 10.8](http://buildbot.e.ip.saba.us:8010/builders/bottle_osx10.8/builds/76/steps/shell/logs/stdio), which doesn't make it past the self-tests.

**Comment by mlubin** [comment]
Has anything in Cbc or its dependencies changed? Why is this happening now?

**Comment by staticfloat** [comment]
Actually, looking at this more closely, does this have anything to do with `Cbc` at all?  This could just be a `julia` nightly bug or something.

**Comment by mlubin** [comment]
Looks like a nightly bug: https://travis-ci.org/JuliaOpt/NLopt.jl/jobs/58512401

**Comment by tkelman** [comment]
I can reproduce on Linux, most likely caused by https://github.com/JuliaLang/julia/pull/10808

**Pull request merged**
